add csv and csvReader
next-cesar-school/next20221-t09-processamento-lote pull request #3
Opened 2022-06-11 18:00 UTC by harryazawa

csv com 15 linhas, leitor lendo chunks de 5 ao invés de todo o documento (há também acréscimo de informações no readme)

2022-06-11 21:07 UTC, MichaelBittencourt requested changes

2022-06-11 21:07 UTC, MichaelBittencourt commented on csvReader.py
> +    df = pd.read_csv('./csv/bancoColaboradores.csv', chunksize=5)
Porque não recebeu o nome do arquivo pelo sys.argv?

2022-06-12 19:19 UTC, harryazawa commented on csvReader.py
> +    df = pd.read_csv('./csv/bancoColaboradores.csv', chunksize=5)
código refatorado e ajustado conforme pedido

2022-06-13 10:52 UTC, joaovitor7 commented on csvReader.py
> +def main():
Booooaaaa

2022-06-13 10:55 UTC, joaovitor7 commented on csvReader.py
> +from flask import Flask
Pode remover o Flask daqui ja que nao vamos precisar usar ele aqui. Mantem somente o leitor e as validacoes aqui.

2022-06-13 10:56 UTC, joaovitor7 approved these changes, later dismissed

2022-06-13 11:12 UTC, MichaelBittencourt commented on csvReader.py
> +    df = pd.read_csv('./csv/bancoColaboradores.csv', chunksize=5)
Vc subiu as alterações?

2022-06-13 15:47 UTC, harryazawa commented on csvReader.py
> +    df = pd.read_csv('./csv/bancoColaboradores.csv', chunksize=5)
sim, eu acidentalmente criei varios commits porque pensei que as alterações não tavam aparecendo, mas indo em files changed o codigo ta inteirinho com as alterações.

2022-06-14 02:32 UTC, MichaelBittencourt approved these changes

2022-06-14 10:13 UTC, joaovitor7 approved these changes

2022-06-14 18:19 UTC, merged